coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 0%
        paths:
          - backend
ignore:
  - "backend/src/main/java/com/karankumar/bookproject/BookProjectApplication.java"

