language: java
coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 0%
    patch: off
ignore:
  - "backend/src/main/java/com/karankumar/bookproject/BookProjectApplication.java"
